tag-name = "{{crate_name}}-v{{version}}"

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[UNRELEASED\\]\\(https?://[^)]+?/compare/(?P<previous>[^)]+)\\.\\.\\.HEAD\\) - DATE"
replace = """## [UNRELEASED](https://github.com/quartiq/minimq/compare/{{tag_name}}...HEAD) - DATE

## [{{version}}](https://github.com/quartiq/minimq/compare/${previous}...{{tag_name}}) - {{date}}"""
exactly = 1
