[package]
name = "mqtt-staging"
version = "0.1.0"
authors = ["Robert Jördens <rj@quartiq.de>"]
edition.workspace = true
description = "Stage bounded objects into embedded storage over MQTT"
repository.workspace = true
readme = "README.md"
categories = ["embedded", "no-std", "network-programming"]
keywords = ["mqtt", "embedded", "no-std", "staging"]
license = "MIT OR Apache-2.0"
rust-version = "1.93"

[lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[dependencies]
defmt = "1.0.1"
heapless = "0.9.1"
itoa = "1"
minimq = { path = "../minimq", version = "0.13" }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde-json-core = { version = "0.6.0", default-features = false }

[dev-dependencies]
critical-section = { version = "1", features = ["std"] }
defmt2log = "0.2.0"
embassy-futures = { version = "0.1.2", default-features = false }
embassy-time = { version = "0.5.1", default-features = false, features = ["std", "generic-queue-8"] }
embedded-io-async = { version = "0.7", features = ["std"] }
env_logger = "0.11"
