[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "mqtt-rpc"
version = "0.1.0"
description = "Async MQTT 5 request/response client"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "Ryan Summers", email = "ryan.summers@vertigo-designs.com" },
    { name = "Robert Jördens", email = "rj@quartiq.de" },
]
dependencies = ["gmqtt>=0.7"]

[project.optional-dependencies]
dev = ["ruff>=0.11"]
test = ["pytest>=8"]

[project.urls]
Homepage = "https://github.com/quartiq/minimq"
Repository = "https://github.com/quartiq/minimq.git"

[project.scripts]
mqtt-rpc = "mqtt_rpc.__main__:main"

[tool.setuptools]
packages = ["mqtt_rpc"]

[tool.ruff]
target-version = "py311"
src = ["mqtt_rpc"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
